import { Seam } from "seam";

/**
 * Server-only Seam client. Throws when SEAM_API_KEY is missing.
 */
export function getSeamClient(): Seam {
  const apiKey = process.env.SEAM_API_KEY;
  if (!apiKey) {
    throw new Error("SEAM_API_KEY is not configured");
  }
  return new Seam({ apiKey });
}

/**
 * Deny access by locking one device.
 */
export async function applyHardwareConstraint(deviceId: string): Promise<void> {
  const trimmedDeviceId = deviceId.trim();
  if (!trimmedDeviceId) {
    throw new Error("deviceId is required");
  }
  const seam = getSeamClient();
  // TODO(Henry): confirm this lock call is the production hardware constraint.
  await seam.locks.lockDoor({ device_id: trimmedDeviceId });
}

/**
 * Provisions a dynamic guest access code for a specific smart lock device via the Seam API.
 * Omitting a code lets Seam generate a random one.
 * @param deviceId The unique identifier of the physical lock hardware.
 * @param tenantName A descriptive label to anchor the code to the guest profile.
 * @returns The unique access_code_id generated by Seam.
 */
export async function createGuestAccessCode(deviceId: string, tenantName: string): Promise<string> {
  const trimmedDeviceId = deviceId.trim();
  const trimmedTenantName = tenantName.trim();
  if (!trimmedDeviceId) {
    throw new Error("deviceId is required");
  }
  if (!trimmedTenantName) {
    throw new Error("tenantName is required");
  }

  const seam = getSeamClient();
  try {
    const accessCode = await seam.accessCodes.create({
      device_id: trimmedDeviceId,
      name: `Guest Code - ${trimmedTenantName}`,
    });
    if (!accessCode.access_code_id) {
      throw new Error("Seam API Code Generation Failed");
    }
    return accessCode.access_code_id;
  } catch (error) {
    if (error instanceof Error && error.message === "Seam API Code Generation Failed") {
      throw error;
    }
    const detail = error instanceof Error ? error.message : "request failed";
    throw new Error(`Seam API Code Generation Failed: ${detail}`);
  }
}
